name: Node.js CICD
 
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t sankalpnagle06/dashboard-backend .

      - name: Publish Image to docker hub
        run: docker push sankalpnagle06/dashboard-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull sankalpnagle06/dashboard-backend:latest

      - name: Delete old container
        run: docker rm -f dashboard-backend-container 

      - name: Create .env file from GitHub secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name dashboard-backend-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' sankalpnagle06/dashboard-backend:latest
